# Generated by Django 4.1.3 on 2022-11-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Profile',
        ),
    ]
